<?php
if ($this->error != null){
    echo '<div class="alert alert-danger">' . $error . '</div>';
}
?>


<div class="row col-md-12">
    <form class="col-md-3" action="" method="post" role="form">
        <div class="form-group">
            <label for="lastname">Nom : </label>
            <input name="lastname" type="text" class="form-control" id="lastname" required placeholder="Entrer votre nom">
        </div>
        <div class="form-group">
            <label for="firstname">Prénom : </label>
            <input name="firstname" type="text" class="form-control" id="firstname" required placeholder="Entrer votre prénom">
        </div>
        <div class="form-group">
            <label for="firstname">Email : </label>
            <input name="email" type="email" class="form-control" id="email" required placeholder="Entrer votre email">
        </div>

        <button type="submit" class="btn btn-default">Enregistrer</button>
    </form>
</div>
<div  class="row clearfix">

</div>

