<form action="./login" method="post" ><div class="row">
        <input  class="col-md-2" type="text" name="login" />
    </div>
    <div class="row">
        <input class="col-md-2"  type="password" name="password" />
    </div>
     <div class="row" >
         <button type="submit" class="btn btn-success">Se connecter</button>
    </div>
</form>
<?php 
    if(isset($this->retour)){
        echo $this->retour;
    }
?>